### ISSUE TITLE
dhlab initialiserer ikke hvis server er nede

### ISSUE THREAD

**Issue by magbb** [NationalLibraryOfNorway/DHLAB#109]
import dhlab

eller

from dhlab import nbtokenizer

feiler når REST APIet er nede. Feilmelding:

```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/magbb/.virtualenvs/dhlab/lib/python3.10/site-packages/dhlab/__init__.py", line 2, in <module>
    from dhlab.text import nbtokenizer
  File "/home/magbb/.virtualenvs/dhlab/lib/python3.10/site-packages/dhlab/text/__init__.py", line 7, in <module>
    from .geo_data import GeoData
  File "/home/magbb/.virtualenvs/dhlab/lib/python3.10/site-packages/dhlab/text/geo_data.py", line 6, in <module>
    spacy = Models()
  File "/home/magbb/.virtualenvs/dhlab/lib/python3.10/site-packages/dhlab/text/parse.py", line 8, in __init__
    self.models = show_spacy_models()
  File "/home/magbb/.virtualenvs/dhlab/lib/python3.10/site-packages/dhlab/api/dhlab_api.py", line 47, in show_spacy_models
    return r.json()
```
Synderen ligger i api.dhlab_api.py og text.geo_data.py. Sistnevnte prøver å laste spacy-modell og den krever en liste tilbake med modellnavn med minst ett element. Så f.eks. ved å hacke det til:

```python
def show_spacy_models():
    """Show available SpaCy model names."""
    try:
        r = requests.get(f"{BASE_URL}/ner_models")
        return r.json()
    except:
        print("DHLAB nede.")
        return ['TEST']
```

i dhlab_api.py, virker det. Burde nok løses i geo_data. Men fint med exception handling i dhlab_api.py også.

**Comment by Ingerid** [comment]
>  Burde nok løses i geo_data. Men fint med exception handling i dhlab_api.py også.

Jeg lar den returnere en tom liste dersom responsen er 404:
https://github.com/NationalLibraryOfNorway/DHLAB/blob/fix/109-import-dhlab-offline/dhlab/api/dhlab_api.py#L66

GeoData får en tom `place_names` dataramme dersom input er None eller API-kallet ikke går gjennom (når `Models().models` ikke har noe på indeks 0). Har lagt til exception-handling med eksplisitte feilmeldinger i en ny, privat metode i GeoData også: 
https://github.com/NationalLibraryOfNorway/DHLAB/blob/fix/109-import-dhlab-offline/dhlab/text/geo_data.py#L18
